version: '3.8'

services:
  voice:
    build: .
    container_name: voice
    restart: always
    env_file:
      - /opt/voice/.env      # .env будет лежать НА СЕРВЕРЕ, вне репозитория
    ports:
      - "127.0.0.1:8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
